### PR TITLE
Add new SCP to enforce 30 for KMS key deletion

### PR DESCRIPTION
**Pull request by jansen-sena**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jansen-sena** [comment]
Approved.

**Comment by liwadman** [comment]
Policy lint's clean and makes logical sense - valuable enterprise control.

Can you please write an update to protect-cloud-platform-resource.md as well,

**Review by jansen-sena — COMMENTED** [review]
I added a new SCP to enforce 30 days for KMS key deletion.

**Review by jansen-sena — COMMENTED** [review]
I added a new SCP to enforce 30 days for KMS key deletion.

**Comment by jansen-sena** [comment]
protect-cloud-platform-resource.md updated.

**Review by SwaraGandhi — APPROVED** [review]

**Pull request merged**
